name: genemap
dependencies:
    - python=3.5
    - future
    - pandas
    - requests
    - pip:
        - requests_cache
        - git+https://github.com/jrderuiter/pybiomart.git
        - git+https://github.com/jrderuiter/genemap.git
